In [2]:
#Buatlah program Numpy dimana didapatkan vektor dengan panjang 10 dan angkanya menyebar merata antara 5 sampai 50
import numpy as np
numbers = np.random.rand(10)
hasil = 5 + (numbers * (50 - 5))
print(hasil)

[25.40801147 35.6603975  44.17391888 37.04842046 43.0558743  17.49055817
 23.98470342  8.31439586 41.06130031 25.23290092]


In [7]:
#Buatlah matriks identitas 3x3 dimana nilai diagonal = 1, sisanya 0
import numpy as np
identity_matriks = np.identity(3)
print(identity_matriks)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#Hitunglah rata rata, variansi dan standar deviasi dari x = np.random.randint(10,31, size = (1,5)
import numpy as np

x = np.random.randint(10, 31, size=(1, 5))
mean = np.mean(x)
variance = np.var(x)

std_deviation = np.std(x)

print("Array x: ", x)
print("Rata-rata: ", mean)
print("Variansi: ", variance)
print("Standar deviasi: ", std_deviation)


Array x:  [[23 14 30 24 18]]
Rata-rata:  21.8
Variansi:  29.76
Standar deviasi:  5.455272678794342


In [9]:
#Hitunglah nilai rata rata dari 2 array numpy dimana arr1 = np.array([3,4]) dan arr2 = np.array([1,0]
import numpy as np

arr1 = np.array([3, 4])
arr2 = np.array([1, 0])

mean_arr1 = np.mean(arr1)
mean_arr2 = np.mean(arr2)

print("Rata-rata array 1: ", mean_arr1)
print("Rata-rata array 2: ", mean_arr2)


Rata-rata array 1:  3.5
Rata-rata array 2:  0.5


In [10]:
#Hitunglah akar pada vektor yang dihasilkan dari pertanyaan nomor 1
import numpy as np

vector = np.array([25, 35, 44, 37, 43, 17, 23, 8, 41, 25])
sqrt_vector = np.sqrt(vector)

print("Vektor: ", vector)
print("Akar dari vektor: ", sqrt_vector)


Vektor:  [25 35 44 37 43 17 23  8 41 25]
Akar dari vektor:  [5.         5.91607978 6.63324958 6.08276253 6.55743852 4.12310563
 4.79583152 2.82842712 6.40312424 5.        ]
